state_file_s3_bucket = "state-file-s3-bucket-dev"
state_file_s3_bucket_logs = "state-file-s3-bucket-logs-dev"
state_lock_dynamodb_table = "state-lock-dynamodb-table-dev"
region = "sa-east-1"
environment = "dev"