[tool.poe.tasks]
lint = "ruff check"
test = "pytest"
pre-build = "rm -rf bundle"
package-src = "cp -r src bundle"
install-plugin = "pip install poetry-plugin-export"
export-deps = "poetry export --without-hashes --only main -f requirements.txt -o requirements.txt"
install-deps = "pip install -r requirements.txt -t bundle"
package-deps = ["install-plugin", "export-deps", "install-deps"]
make-bundle = ["package-src", "package-deps"]
build = ["pre-build", "make-bundle"]
