name: "delete_feature_branch"

on:
  delete:

jobs:
  delete-infra:
    if: github.event.ref_type == 'branch'
    name: "Delete Infra"
    permissions:
      issues: write
    uses: ./.github/workflows/destroy_infra_workflow.yaml
    with:
      terraform_version: "1.8.3"
      environment: "dev"
      branch: ${{ github.event.ref }}
      aws_region: "sa-east-1"
      aws_assume_role_arn: "aws_assume_role_arn"
      aws_state_file_s3_bucket: "aws_state_file_s3_bucket"
      aws_state_lock_dynamodb_table: "aws_state_lock_dynamodb_table"
