name: "deploy-feature-branch"

on:
  push:
    branches:
      - "np**"
  pull_request:
    branches:
      - "np**"

jobs:
  build-lambdas:
    name: "Build Lambdas"
    uses: ./.github/workflows/python-workflow.yaml

  deploy-infra:
    name: "Deploy Infra to AWS"
    permissions:
      issues: write
    uses: ./.github/workflows/apply-infra-workflow.yaml
    needs: [build-lambdas]
    with:
      terraform_version: "1.8.3"
      environment: "dev"
      branch: ${{ github.head_ref || github.ref_name }}
      aws-region: "sa-east-1"
      aws-assume-role-arn: "aws-assume-role-arn"
      aws-state-file-s3-bucket: "aws-state-file-s3-bucket"
      aws-state-lock-dynamodb-table: "aws-state-lock-dynamodb-table"
