name: "destroy-feature-branch"

on:
  delete:

jobs:
  destroy-infra:
    if: github.event.ref_type == 'branch'
    name: "Destroy AWS resources"
    permissions:
      issues: write
    uses: ./.github/workflows/terraform-workflow.yaml
    with:
      terraform_version: "1.8.3"
      destroy: true
      environment: "dev"
      branch: ${{ github.event.ref }}
      aws-region: "sa-east-1"
      aws-assume-role-arn: "aws-assume-role-arn"
      aws-state-file-s3-bucket: "aws-state-file-s3-bucket"
      aws-state-lock-dynamodb-table: "aws-state-lock-dynamodb-table"
