name: "run_python_workflow"

on: workflow_dispatch

jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read lambdas configuration
        id: set-matrix
        run: |
          LAMBDA_CONFIG="$(jq -c . lambda_config.json)"
          echo "lambda_config=$(echo $LAMBDA_CONFIG)" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.set-matrix.outputs.lambda_config }}

  list-test-build:
    name: "Lint, Test and Build"
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lambda_config_obj: ${{ fromJson(needs.setup.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display lambda configuration
        run: |
          echo "pythonVersion: ${{ matrix.lambda_config_obj.pythonVersion }}"
          echo "lambdaName: ${{ matrix.lambda_config_obj.lambdaName }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.lambda_config_obj.pythonVersion }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Define virtual environment cache
        uses: actions/cache@v3
        with:
          path: ./lambdas/${{ matrix.lambda_config_obj.lambdaName }}/.venv
          key: venv-${{ hashFiles(format('./lambdas/{0}/poetry.lock', matrix.lambda_config_obj.lambdaName)) }}

      - name: Install dependencies
        working-directory: ./lambdas/${{ matrix.lambda_config_obj.lambdaName }}
        run: poetry install

      - name: Lint code
        working-directory: ./lambdas/${{ matrix.lambda_config_obj.lambdaName }}
        run: poetry run poe lint

      - name: Test code
        working-directory: ./lambdas/${{ matrix.lambda_config_obj.lambdaName }}
        run: poetry run poe test

      - name: Upload artifact to inspect the code quality
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.lambda_config_obj.lambdaName }}_cov_artifact
          path: |
            ./lambdas/${{ matrix.lambda_config_obj.lambdaName }}/.coverage
            ./lambdas/${{ matrix.lambda_config_obj.lambdaName }}/coverage.xml

      - name: Build code
        working-directory: ./lambdas/${{ matrix.lambda_config_obj.lambdaName }}
        run: poetry run poe build

      - name: Upload artifact to distribute the code
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.lambda_config_obj.lambdaName }}_release_artifact
          path: ./lambdas/${{ matrix.lambda_config_obj.lambdaName }}/bundle
